application: goplacecreature
version: 1
runtime: go
api_version: go1

admin_console:
  pages:
  - name: Fixture Importer
    url: /admin

handlers:
- url: /static
  static_dir: static
- url: /admin
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
